service: super-duper-quacamole
frameworkVersion: '3'
configValidationMode: warn
	
package:
  individually: true
    
provider:
  name: ${file(./config.yml):aws.name}
  runtime: ${file(./config.yml):aws.runtime}
  stage: ${file(./config.yml):aws.stage}
  region: ${file(./config.yml):aws.region}
  deploymentBucket:
    name: ${file(./config.yml):aws.deploymentBucket.name}
  environment:
    TELEGRAM_TOKEN: ${file(./config.yml):telegramBotToken}
    RDS_HOSTNAME: ${file(./config.yml):aws.database.host}
    RDS_USERNAME: ${file(./config.yml):aws.database.user}
    RDS_PASSWORD: ${file(./config.yml):aws.database.password}
    RDS_DATABASE: ${file(./config.yml):aws.database.database}
    GW_URL:   # https://www.richdevelops.dev/how-do-i-get-my-api-gateway-url
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "ApiGatewayRestApi"
          - ".execute-api.${file(./config.yml):aws.region}.amazonaws.com/${file(./config.yml):aws.stage}"

functions:
  bot:
    handler: src/bot.handler
    logRetentionInDays: 7
    events:
      - http:
          path: bot
          method: post
# TODO
#  notifications:
#    handler: src/tasks/notifications.handler
#    events:
#      - schedule: rate(1 hour)
#  webScraping:
#    handler: src/tasks/webScraping.handler
#    events:
#      - schedule: rate(24 hours)

plugins:
  - serverless-offline
  - serverless-plugin-typescript