service: super-duper-quacamole

provider:
  name: ${file(./config.yml):aws.name}
  runtime: ${file(./config.yml):aws.runtime}
  stage: ${file(./config.yml):aws.stage}
  region: ${file(./config.yml):aws.region}
# TODO  
#  environment:
#    RDS_HOSTNAME: ${file(./config.yml):aws.database.host}
#    RDS_USERNAME: ${file(./config.yml):aws.database.user}
#    RDS_PASSWORD: ${file(./config.yml):aws.database.password}
#    RDS_DATABASE: ${file(./config.yml):aws.database.database}

functions:
  bot:
    handler: src/bot.handler
    events:
      - http:
          path: bot
          method: post
# TODO
#  notifications:
#    handler: src/tasks/notifications.handler
#    events:
#      - schedule: rate(1 hour)
#  webScraping:
#    handler: src/tasks/webScraping.handler
#    events:
#      - schedule: rate(24 hours)

plugins:
  - serverless-offline