service: super-duper-quacamole
frameworkVersion: '3'
configValidationMode: warn
	
package:
  individually: true

provider:
  name: ${file(./config.${opt:stage, 'dev'}.yml):aws.name}
  runtime: ${file(./config.${opt:stage, 'dev'}.yml):aws.runtime}
  stage: ${file(./config.${opt:stage, 'dev'}.yml):aws.stage}
  region: ${file(./config.${opt:stage, 'dev'}.yml):aws.region}
  deploymentBucket:
    name: ${file(./config.${opt:stage, 'dev'}.yml):aws.deploymentBucket.name}
  environment:
    TELEGRAM_TOKEN: ${file(./config.${opt:stage, 'dev'}.yml):telegramBotToken}
    RDS_HOSTNAME: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.host}
    RDS_USERNAME: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.user}
    RDS_PASSWORD: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.password}
    RDS_DATABASE: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.database}

functions:
  bot:
    handler: src/bot.handler
    logRetentionInDays: 7
    events:
      - http:
          path: bot
          method: post
  setTelegramWebhook:
    handler: src/bot.setTelegramWebhook
    logRetentionInDays: 7          
# TODO
#  notifications:
#    handler: src/tasks/notifications.handler
#    events:
#      - schedule: rate(1 hour)
#  webScraping:
#    handler: src/tasks/webScraping.handler
#    events:
#      - schedule: rate(24 hours)

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-scripts

custom:
  stageSpecificConfigs:
    dev:
      provider:
        environment:
          GW_URL:   # https://www.richdevelops.dev/how-do-i-get-my-api-gateway-url
            Fn::Join:
              - ""
              - - "https://"
                - Ref: "ApiGatewayRestApi"
                - ".execute-api.${file(./config.${opt:stage, 'dev'}.yml):aws.region}.amazonaws.com/${file(./config.${opt:stage, 'dev'}.yml):aws.stage}"
      scripts:
        hooks:
          'deploy:finalize': serverless invoke -f setTelegramWebhook
    prod:
      provider:
        environment:
          GW_URL:
            Fn::Join:
              - ""
              - - "https://"
                - Ref: "ApiGatewayRestApi"
                - ".execute-api.${file(./config.${opt:stage, 'prod'}.yml):aws.region}.amazonaws.com/${file(./config.${opt:stage, 'prod'}.yml):aws.stage}"
      scripts:
        hooks:
          'deploy:finalize': serverless invoke -f setTelegramWebhook