service: super-duper-quacamole
frameworkVersion: '3'
configValidationMode: warn
	
package:
  individually: true
  include:
    - src/subscriptions.json

provider:
  name: ${file(./config.${opt:stage, 'dev'}.yml):aws.name}
  runtime: ${file(./config.${opt:stage, 'dev'}.yml):aws.runtime}
  stage: ${file(./config.${opt:stage, 'dev'}.yml):aws.stage}
  region: ${file(./config.${opt:stage, 'dev'}.yml):aws.region}
  deploymentBucket:
    name: ${file(./config.${opt:stage, 'dev'}.yml):aws.deploymentBucket.name}
  environment:
    TELEGRAM_TOKEN: ${file(./config.${opt:stage, 'dev'}.yml):telegramBotToken}
    S3_BUCKET: ${file(./config.${opt:stage, 'dev'}.yml):aws.deploymentBucket.name} # to store chat ids
    CHAT_DATA_FOLDER: ${file(./config.${opt:stage, 'dev'}.yml):chatDataFolder}
    RDS_HOSTNAME: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.host}
    RDS_USERNAME: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.user}
    RDS_PASSWORD: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.password}
    RDS_DATABASE: ${file(./config.${opt:stage, 'dev'}.yml):aws.database.database}
    GW_URL:   # https://www.richdevelops.dev/how-do-i-get-my-api-gateway-url
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "ApiGatewayRestApi"
          - ".execute-api.${file(./config.${opt:stage, 'dev'}.yml):aws.region}.amazonaws.com/${file(./config.${opt:stage, 'dev'}.yml):aws.stage}"

custom:
  scripts:
    hooks:
      'deploy:finalize': serverless invoke -f setTelegramWebhook

functions:
  bot:
    handler: src/bot.handler
    logRetentionInDays: 7
    events:
      - http:
          path: bot
          method: post
  setTelegramWebhook:
    handler: src/bot.setTelegramWebhook
    logRetentionInDays: 7
  rabo:
    handler: src/tasks/webScraping.rabo
    logRetentionInDays: 7
  sendNotificationToSubscribers:
    handler: src/bot.sendNotificationToSubscribers
    logRetentionInDays: 7
    # events:
    #   - schedule: rate(5 minutes)
# TODO
#  notifications:
#    handler: src/tasks/notifications.handler
#    events:
#      - schedule: rate(1 hour)
#  webScraping:
#    handler: src/tasks/webScraping.handler
#    events:
#      - schedule: rate(24 hours)

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-scripts